apiVersion: v1
kind: ServiceAccount
metadata:
  name: orion-postgres
  namespace: orion-prod
  labels:
    app.kubernetes.io/name: orion-postgres
    app.kubernetes.io/instance: orion-prod
    app.kubernetes.io/part-of: orion
    app.kubernetes.io/managed-by: platform
  annotations:
    metacortex.io/owner: plataforma-sre
automountServiceAccountToken: false
