# 3.5 · 3.4
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nyx-postgres
  namespace: nyx-dev
  labels:
    app.kubernetes.io/name: nyx-postgres
    app.kubernetes.io/instance: nyx-dev
    app.kubernetes.io/part-of: nyx
    app.kubernetes.io/managed-by: platform
  annotations:
    metacortex.io/owner: plataforma-sre
automountServiceAccountToken: false
